name: Karate CI
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu_latest

    steps:
    - uses: actions-checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and Test with Maven
      run: mvn -B test
    - name: Generate Test Reports
      run: mvn karate:report
    - name: Upload Karate Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports
